[package]
name = "twitch_commands"
version = "0.1.0"
authors = ["Giulio Caprino <julo134@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
twitchchat = "0.11.8"
tokio = { version = "0.2", features = ["rt-threaded", "macros"] }
futures = "0.3.5"
async-stream = "0.2.1"
dotenv = "0.15.0"
enigo = "0.0.14"
async-trait = "0.1.37"
mockall = "0.8.1"
tokio-test = "0.2.1"
libc = "0.2.77"
toml = "0.5.6"
serde = { version = "1.0.116", features = ["derive"] }

[build-dependencies]
cc = "1.0.60"
