version = "1.0"

[twitch_stream]
user = "Bot_Username"
token = "oauth:some_code"
channel = "Channel_Name"

[mapping]
    [[mapping.config]]
    source = "message"
    id = "up"
    actions = ["kd38"]

    [[mapping.config]]
    source = "message"
    id = "updown"
    actions = ["kd40", "w1000", "kd38"]
